### ISSUE TITLE
FileNotFoundError: The file "C" does not exist or is not a regular file.

### ISSUE THREAD

**Issue by faniAhmed** [sciapp/github-binary-upload#4]
it is giving error file not found although I gave full path to the file.zip. I am new and could not find a single example on how to use this so I have been facing many errors too.
`
from github_binary_upload import publish_release_from_tag

project = "slarti-com/slarti-electron-wrapper"
tag = "v1.0.2"
assets = "C:\\Users\\Farhan Ahmed\\Desktop\\code\\f1"
github_server = "github.com"
username = ""
password = ""
publish_release_from_tag(
    project, tag, assets, github_server, username, password
)
`
![image](https://user-images.githubusercontent.com/89826402/169016495-68d5593d-c3c5-4412-a058-84417ae598f5.png)

**Comment by IngoMeyer441** [comment]
We never tested this piece of software on a Windows host, but the source code *should* not be platform specific. I can have a look  at this later.

**Comment by faniAhmed** [comment]
OK. Just to confirm username is gmail and password is the token

**Comment by IngoMeyer441** [comment]
Ok, the problem is, that assets must be a list of strings, not a single string. If a single string is passed, the string itself is iterated and the script tries to open the first letter (`C`).

**Comment by faniAhmed** [comment]
Thanks it is working
